//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMidterm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PolicyPackage
    {
        public int PolicyID { get; set; }
        public string Package { get; set; }
        public Nullable<double> Health { get; set; }
        public Nullable<double> Life { get; set; }
        public Nullable<double> Premium { get; set; }
    }
}
